[package]
name = "alvorada"
version = "0.1.0"
edition = "2024"
authors = ["Afonso Lage <afonsolage@gmail.com>"]
description = "A 2D game built with Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/afonsolage/alvorada"
readme = "README.md"
exclude = [".github/", "web/", "docs/"]

[dependencies]
bevy = { version = "0.18", features = ["webgl2"] }

# Enable a small amount of optimization in debug mode to speed up iteration
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"

# Optimize for WASM: favor smaller binary size
[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "thin"
strip = "debuginfo"
